//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentSerial { get; set; }
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> sys_DateCreation { get; set; }
        public Nullable<System.DateTime> sys_DateLastModification { get; set; }
        public string Gender { get; set; }
    }
}
